#
# build-s6.yml
# Build and push the fw to a WebDAV server
#

name: Build for Fysetc S6

on:
  push:
    branches:
    - leo_1S_S6
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  build_fw:
    name: Build for Fysetc S6

    runs-on: ubuntu-latest

    steps:

    - name: Set Time Zone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "Europe/Prague"
        
    - name: Check out the PR
      uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Select Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update
    - name: Build the FW
      run: |
        pio run -j7
    - name: Upload the fw    
      run: |
        curl --user "${{ secrets.DAV_USER }}:${{ secrets.DAV_PASS }}" -T ".pio/build/FYSETC_S6_8000/firmware.bin" "${{ secrets.DAV_SERVER }}/${{ secrets.DAV_PATH }}/firmware_`date +%d_%m_%y_%H_%M`_1S_S6.bin" --anyauth
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware.bin
        path: .pio/build/FYSETC_S6_8000/firmware.bin